'use client';

import { useMemo, useState } from 'react';

type Tx = { date:string; description:string; category:string; account:string; amount:number; type:'income'|'expense'; };

const transactions: Tx[] = [
  {date:'Sep 9, 2026',description:'Client payment — Acme Design',category:'Services',account:'Business Checking',amount:4200,type:'income'},
  {date:'Sep 8, 2026',description:'Office rent',category:'Rent',account:'Business Checking',amount:1450,type:'expense'},
  {date:'Sep 7, 2026',description:'QuickBooks subscription',category:'Software',account:'Business Credit Card',amount:65,type:'expense'},
  {date:'Sep 5, 2026',description:'Tax preparation deposit',category:'Tax Services',account:'Business Checking',amount:1800,type:'income'},
  {date:'Sep 3, 2026',description:'Office supplies',category:'Office',account:'Business Credit Card',amount:238,type:'expense'},
];

const nav = [['⌂','Dashboard'],['↔','Transactions'],['$','Income'],['−','Expenses'],['▣','Invoices'],['♙','Clients'],['▤','Reports'],['✓','Taxes'],['✉','Contact']];
const BUSINESS_PHONE = process.env.NEXT_PUBLIC_CONTACT_PHONE || '424-250-9420';
const BUSINESS_EMAIL = process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'Cassedani@gmail.com';
function money(n:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)}

export default function Home(){
  const [active,setActive]=useState('Dashboard'); const [query,setQuery]=useState(''); const [showAdd,setShowAdd]=useState(false); const [toast,setToast]=useState(''); const [period,setPeriod]=useState('This month');
  const filtered=useMemo(()=>transactions.filter(t=>`${t.description} ${t.category} ${t.account}`.toLowerCase().includes(query.toLowerCase())),[query]);
  const notify=(msg:string)=>{setToast(msg);setTimeout(()=>setToast(''),2500)};
  return <main className="shell"><aside className="sidebar"><div className="brand"><div className="logo">C</div><div><strong>Cassedani</strong><span>BOOKKEEPING & TAXES</span></div></div><div className="workspace">Cassedani Corp <span>⌄</span></div><nav>{nav.map(([icon,label])=><button key={label} className={active===label?'active':''} onClick={()=>setActive(label)}><i>{icon}</i>{label}</button>)}</nav><div className="sideBottom"><button><i>⚙</i>Settings</button><div className="user"><div className="avatar">CC</div><div><b>Cassedani Corp</b><small>Owner</small></div></div></div></aside>
  <section className="content"><header className="topbar"><div><p className="eyebrow">{active === 'Dashboard' ? 'Overview' : active}</p><h1>{active}</h1></div><div className="topActions"><button className="iconBtn">⌕</button><button className="iconBtn">♢</button><button className="primary" onClick={()=>setShowAdd(true)}>+ Add transaction</button></div></header>
  {active==='Contact'?<ContactPage phone={BUSINESS_PHONE} email={BUSINESS_EMAIL}/>:active!=='Dashboard'?<div className="panel pagePanel"><div className="panelHead"><div><h2>{active}</h2><p>Manage your {active.toLowerCase()} in one place.</p></div><button className="primary" onClick={()=>setShowAdd(true)}>+ Add new</button></div><div className="emptyState"><div className="emptyIcon">{active==='Reports'?'▤':'✦'}</div><h3>{active==='Taxes'?'Tax center':`${active} workspace`}</h3><p>This starter workspace is ready for your real data, filters, forms and database integration.</p><button className="secondary" onClick={()=>notify('Workspace selected')}>Get started</button></div></div>:<>
  <div className="welcome"><div><h2>Good morning, Cassedani Corp 👋</h2><p>Here’s what’s happening with your business.</p></div><select value={period} onChange={e=>setPeriod(e.target.value)}><option>This month</option><option>Last month</option><option>This quarter</option><option>This year</option></select></div>
  <div className="cards"><Metric title="Revenue" value="$18,450" change="12.4%" positive sub="vs. previous period" icon="↗"/><Metric title="Expenses" value="$6,280" change="4.8%" positive sub="vs. previous period" icon="↘"/><Metric title="Net profit" value="$12,170" change="16.2%" positive sub="vs. previous period" icon="$"/><Metric title="Outstanding" value="$3,750" change="3 invoices" positive={false} sub="need attention" icon="!"/></div>
  <div className="grid2"><div className="panel"><div className="panelHead"><div><h3>Cash flow</h3><p>Revenue vs. expenses</p></div><button className="ghost">Last 6 months⌄</button></div><div className="chart"><div className="ylabels"><span>$20k</span><span>$15k</span><span>$10k</span><span>$5k</span><span>$0</span></div><div className="plot"><div className="gridlines"><i/><i/><i/><i/><i/></div><svg viewBox="0 0 620 190" preserveAspectRatio="none"><polyline points="0,125 105,103 205,115 310,67 415,82 520,38 620,50"/><polyline className="expense" points="0,157 105,143 205,148 310,125 415,133 520,111 620,121"/></svg><div className="months"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></div></div><div className="legend"><span><i className="dot income"/>Revenue</span><span><i className="dot expense"/>Expenses</span></div></div><div className="panel"><div className="panelHead"><div><h3>Expense breakdown</h3><p>Where your money goes</p></div><button className="ghost">View report →</button></div><div className="breakdown"><Bar name="Payroll" value="$2,800" pct={45}/><Bar name="Rent" value="$1,450" pct={23}/><Bar name="Software" value="$680" pct={11}/><Bar name="Office" value="$510" pct={8}/><Bar name="Other" value="$840" pct={13}/></div></div></div>
  <div className="panel transactions"><div className="panelHead"><div><h3>Recent transactions</h3><p>Your latest bookkeeping activity</p></div><div className="filters"><input placeholder="Search transactions" value={query} onChange={e=>setQuery(e.target.value)}/><button className="ghost">Filter⌄</button></div></div><table><thead><tr><th>DATE</th><th>DESCRIPTION</th><th>CATEGORY</th><th>ACCOUNT</th><th>AMOUNT</th></tr></thead><tbody>{filtered.map((t,i)=><tr key={i}><td>{t.date}</td><td><b>{t.description}</b></td><td><span className="tag">{t.category}</span></td><td>{t.account}</td><td className={t.type==='income'?'incomeText':'expenseText'}>{t.type==='income'?'+':'−'}{money(t.amount)}</td></tr>)}</tbody></table><div className="tableFoot">Showing {filtered.length} of {transactions.length} transactions <button onClick={()=>setActive('Transactions')}>View all →</button></div></div></>}
  </section>{toast&&<div className="toast">✓ {toast}</div>}{showAdd&&<div className="modalWrap" onClick={()=>setShowAdd(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><h2>Add transaction</h2><p>Record income or an expense.</p></div><button onClick={()=>setShowAdd(false)}>×</button></div><label>Type<select><option>Income</option><option>Expense</option></select></label><label>Description<input placeholder="e.g. Client payment"/></label><div className="two"><label>Amount<input type="number" placeholder="0.00"/></label><label>Category<select><option>Services</option><option>Office</option><option>Rent</option><option>Software</option><option>Tax Services</option></select></label></div><div className="modalActions"><button className="secondary" onClick={()=>setShowAdd(false)}>Cancel</button><button className="primary" onClick={()=>{setShowAdd(false);notify('Transaction saved')}}>Save transaction</button></div></div></div>}</main>
}

function ContactPage({phone,email}:{phone:string;email:string}){const [form,setForm]=useState({name:'',email:'',phone:'',service:'Bookkeeping',message:''});const [sent,setSent]=useState(false);const submit=(e:React.FormEvent)=>{e.preventDefault();const body=`New client inquiry\n\nName: ${form.name}\nEmail: ${form.email}\nPhone: ${form.phone}\nService: ${form.service}\n\nMessage:\n${form.message}`;window.location.href=`mailto:${email}?subject=${encodeURIComponent('New Cassedani Corp client inquiry')}&body=${encodeURIComponent(body)}`;setSent(true)};const callHref=`tel:${phone.replace(/[^+\d]/g,'')}`;return <div className="contactLayout"><div className="contactIntro"><span className="contactKicker">NEW CLIENTS WELCOME</span><h2>Let’s take bookkeeping off your plate.</h2><p>Prospective clients can reach Cassedani Corp directly, tell us what they need, and request a conversation about bookkeeping or tax services.</p><div className="contactCards"><a className="contactCard" href={callHref}><span className="contactCardIcon">☎</span><div><b>Call Cassedani Corp</b><small>{phone}</small></div></a><a className="contactCard" href={`mailto:${email}`}><span className="contactCardIcon">✉</span><div><b>Email us</b><small>{email}</small></div></a></div></div><form className="panel contactForm" onSubmit={submit}><div className="panelHead"><div><h3>Contact Cassedani Corp</h3><p>Tell us a little about what you need.</p></div></div><div className="formGrid"><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><label>Email address<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><label>Phone number<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="(555) 555-5555"/></label><label>What do you need?<select value={form.service} onChange={e=>setForm({...form,service:e.target.value})}><option>Bookkeeping</option><option>Tax preparation</option><option>Bookkeeping + taxes</option><option>Business consultation</option><option>Something else</option></select></label></div><label>Message<textarea required value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Tell us about your business and how we can help..."/></label><div className="formBottom"><button className="primary" type="submit">Send inquiry →</button></div>{sent&&<p className="formSuccess">Your inquiry is ready. Your email app should open with the details addressed to Cassedani Corp.</p>}</form></div>}
function Metric({title,value,change,sub,icon,positive}:{title:string,value:string,change:string,sub:string,icon:string,positive:boolean}){return <div className="metric"><div className="metricTop"><span>{title}</span><div className="metricIcon">{icon}</div></div><strong>{value}</strong><div><span className={positive?'up':'attention'}>{positive?'↑ ':''}{change}</span> <small>{sub}</small></div></div>}
function Bar({name,value,pct}:{name:string,value:string,pct:number}){return <div className="barRow"><div><span>{name}</span><b>{value}</b></div><div className="bar"><i style={{width:`${pct}%`}}/></div></div>}
